<?php
/**
 * Flagbit_FactFinder
 *
 * @category  Mage
 * @package   Flagbit_FactFinder
 * @copyright Copyright (c) 2010 Flagbit GmbH & Co. KG (http://www.flagbit.de/)
 */

/**
 * Template
 * 
 * Business User Cockpit Template
 * 
 * @category  Mage
 * @package   Flagbit_FactFinder
 * @copyright Copyright (c) 2010 Flagbit GmbH & Co. KG (http://www.flagbit.de/)
 * @author    Joerg Weller <weller@flagbit.de>
 * @version   $Id$
 */
?>
<iframe src="<?php echo $this->getAuthenticationUrl();?>" id="factfinder_cockpit_frame" style="width:100%; height:600px;"  name="factfinder_cockpit_frame" scrolling="auto"></iframe>
