<?php
/**
 * Flagbit_FactFinder
 *
 * @category  Mage
 * @package   Flagbit_FactFinder
 * @copyright Copyright (c) 2010 Flagbit GmbH & Co. KG (http://www.flagbit.de/)
 */

/**
 * Slider HTML Template
 * 
 * @category  Mage
 * @package   Flagbit_FactFinder
 * @copyright Copyright (c) 2010 Flagbit GmbH & Co. KG (http://www.flagbit.de/)
 * @author    Joerg Weller <weller@flagbit.de>
 * @version   $Id$
 */
?>

<style type="text/css"><!--
input.slider-label {
	background-color: #F1F1F1;
	border: 1px solid #ACACAC;
	font-size: 9px;
	height: 20px;
	margin: 10px 0 0;
	text-align: center;
	width: 40px;
}

input.slider-range-min {
	float: left;
}

input.slider-range-max {
	float: right;
}

div.slider {
	margin: 10px 0;
	background-color: #555;
	height:10px;
	position: relative;
}

span.slider-span {
	position: absolute;
	background-color: #6683B4;
	height: 10px;
}

div.slider div.handle {
	width: 10px;
	height: 18px;
	background-color: #F6F6F6;
	border: 1px solid #7F7F7F;
	cursor:move;
	position: absolute;
	margin-top: -5px;
}
--></style>

<ol>
<?php foreach ($this->getItems() as $_item): ?>
	<li>
		<input type="text" readonly="readonly" class="slider-label slider-range-min" value="<?php echo $this->getSelectedMin(), ' ', $this->getUnit(); ?>" />
		<input type="text" readonly="readonly" class="slider-label slider-range-max" value="<?php echo $this->getSelectedMax(), ' ', $this->getUnit(); ?>" />
		<div style="clear: both;"></div>
		<div id="<?php echo base64_encode($this->getValue());?>_slider" class="slider" style="width: 170px;">
			<span id="<?php echo base64_encode($this->getValue());?>_span" class="slider-span"></span>
			<div class="handle"></div>
			<div class="handle"></div>
		</div>
		<script type="text/javascript" language="javascript"> 
		//<![CDATA[
		
			(function() {
				var slider = $('<?php echo base64_encode($this->getValue());?>_slider');
				var minLabel = slider.siblings().grep(new Selector('.slider-range-min'))[0];
				var maxLabel = slider.siblings().grep(new Selector('.slider-range-max'))[0];

				new Control.Slider(slider.select('.handle'), slider, {
					range: $R(<?php echo $this->getAbsoluteMin();?>, <?php echo $this->getAbsoluteMax();?>),
					values: $R(<?php echo $this->getAbsoluteMin();?>, <?php echo $this->getAbsoluteMax();?>),
					sliderValue: [<?php echo $this->getSelectedMin();?>, <?php echo $this->getSelectedMax();?>],
					restricted: true,
					spans: ["<?php echo base64_encode($this->getValue());?>_span"],
					onSlide: function(values) {
						minLabel.setValue(values[0] + " <?php echo $this->getUnit();?>");
						maxLabel.setValue(values[1] + " <?php echo $this->getUnit();?>");
					},
					onChange: function(values) { 
						var url = decodeURI('<?php echo $_item->getUrl() ?>'); 
						window.location.href= url.replace('[VALUE]',values[0] + '+-+' + values[1]);
					}
				});
			})();
		//]]>
		</script>
	</li>
<?php endforeach ?>
</ol>
