<?php
/**
 * Flagbit_FactFinder
 *
 * @category  Mage
 * @package   Flagbit_FactFinder
 * @copyright Copyright (c) 2010 Flagbit GmbH & Co. KG (http://www.flagbit.de/)
 */

/**
 * Slider HTML Template
 * 
 * @category  Mage
 * @package   Flagbit_FactFinder
 * @copyright Copyright (c) 2010 Flagbit GmbH & Co. KG (http://www.flagbit.de/)
 * @author    Joerg Weller <weller@flagbit.de>
 * @version   $Id$
 */
?>
<ol>
<?php foreach ($this->getItems() as $_item): ?>
    <li>	
		<div id="<?php echo base64_encode($this->getValue());?>" style="width: 170px;padding:10px 0px;"></div>
		<script type="text/javascript" language="javascript"> 
		//<![CDATA[
		
			Event.observe(document, 'ffslider:init', function(event){	
					oneTouchSlider.addSlider({
						hostElementId:'<?php echo base64_encode($this->getValue());?>',
						leftBorder: <?php echo $this->getAbsoluteMin();?>,
						rightBorder: <?php echo $this->getAbsoluteMax();?>,
						currentLeft: <?php echo $this->getSelectedMin();?>,
						currentRight: <?php echo $this->getSelectedMax();?>,
						unit:"<?php echo $this->getUnit();?>",
						callback:function(left, right){
							var url = decodeURI('<?php echo $_item->getUrl() ?>'); 
							window.location.href= url.replace('[VALUE]',left + '+-+' + right);
						}
					});	
				}
			);
		//]]>
		</script>		
    </li>
<?php endforeach ?>
</ol>
