<?php
/**
 * FACTFinder_Asn
 *
 * @category Mage
 * @package FACTFinder_Asn
 * @author Flagbit Magento Team <magento@flagbit.de>
 * @copyright Copyright (c) 2016, Flagbit GmbH & Co. KG
 * @license https://opensource.org/licenses/MIT  The MIT License (MIT)
 * @link http://www.flagbit.de
 */
?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/factfinder_onetouchslider/de.factfinder.asn.slider.OneTouchSlider.nocache.js'); ?>"></script>
<script type="text/javascript">
    oneTouchSliderOnLoad = function() {
        document.fire("ffslider:init");
    }
</script>