<?php
/**
 * FACTFinder_Campaigns
 *
 * @category Mage
 * @package FACTFinder_Campaigns
 * @author Flagbit Magento Team <magento@flagbit.de>
 * @copyright Copyright (c) 2015, Flagbit GmbH & Co. KG
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link http://www.flagbit.de
 */
?>

<!-- ff product advisory template -->
<?php if ($questions = $this->getActiveQuestions()): ?>
    <?php foreach ($questions as $question): ?>
    <div class="factfinder-advisorCampaign">
        <p class="factfinder-advisorCampaign-question"><?php echo $question->getText() ?></p>
        <p>
        <?php foreach ($question->getAnswers() as $answer): ?>
            <a class="factfinder-advisorCampaign-answer" href="<?php echo $answer->getParams() ?>"><?php echo $answer->getText() ?></a>
        <?php endforeach; ?>
        </p>
    </div>
    <?php endforeach; ?>
<?php endif; ?>