<div class="ffcampaigntext"><?php echo $this->getText(); ?></div>

<?php
// this is an example, how to use the pushed products
// note, that to have any of the products attributes in this collection, you must first join them
// using method addAttributeToSelect();
$pushedProducts = $this->getPushedProductsCollection();
//$pushedProducts->addAttributeToSelect('name');
?>
<?php if (count($pushedProducts)): ?>
    <?php //customize here the pushed products output ?>
    <?php foreach ($pushedProducts as $product): ?>
        <?php //echo $product->getName(); ?>
    <?php endforeach;  ?>
<?php endif; ?>