<?php
/**
 * FACTFinder_Campaigns
 *
 * @category Mage
 * @package FACTFinder_Campaigns
 * @author Flagbit Magento Team <magento@flagbit.de>
 * @copyright Copyright (c) 2015, Flagbit GmbH & Co. KG
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link http://www.flagbit.de
 */
?>

<div class="ffcampaigntext"><?php echo $this->getText(); ?></div>

<?php
// this is an example, how to use the pushed products
// note, that to have any of the products attributes in this collection, you must first join them
// using method addAttributeToSelect();
$pushedProducts = $this->getPushedProductsCollection();
//$pushedProducts->addAttributeToSelect('name');
?>
<?php if (count($pushedProducts)): ?>
    <?php //customize here the pushed products output ?>
    <?php foreach ($pushedProducts as $product): ?>
        <?php //echo $product->getName(); ?>
    <?php endforeach;  ?>
<?php endif; ?>