<?php
/**
 * FACTFinder_Suggest
 *
 * @category Mage
 * @package FACTFinder_Suggest
 * @author Flagbit Magento Team <magento@flagbit.de>
 * @copyright Copyright (c) 2016 Flagbit GmbH & Co. KG
 * @license https://opensource.org/licenses/MIT  The MIT License (MIT)
 * @link http://www.flagbit.de
 *
 */
/*
 * Advanced Template to replace Javascript Suggest
 * NOTICE: This template will only work if suggests are requested from the proxy
 * (see option in section "FACT-Finder Config Data" in Magento's backend)!
 */
?>
<?php $catalogSearchHelper = $this->helper('catalogsearch'); ?>
<form id="search_mini_form" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" method="get">
    <div class="form-search">
        <div class="input-box">
            <label for="search"><?php echo $this->__('Search:') ?></label>
            <input id="search" type="search" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>"
                   value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text required-entry"
                   maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>"
                   placeholder="<?php echo $this->__('Search entire store here...') ?>" />
            <button type="submit" title="<?php echo $this->__('Search') ?>" class="button search-button">
                <span><span><?php echo $this->__('Search') ?></span></span>
            </button>
        </div>
        <div id="search_autocomplete" class="search-autocomplete advanced-suggest"></div>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var searchForm;
    <?php if (Mage::helper('factfinder')->isEnabled('suggest')): ?>
        searchForm = new FactFinderSuggest(
            'search_mini_form', 'search',
            '<?php echo addslashes($this->__('Search entire store here...')); ?>',
            <?php echo $this->getTranslationsAsJson(); ?>,
            '<?php echo Mage::getStoreConfig('factfinder/search/channel'); ?>'
        );
    <?php else: ?>
        searchForm = new Varien.searchForm('search_mini_form', 'search',
            '<?php echo addslashes($this->__('Search entire shop here...')); ?>'
        );
    <?php endif; ?>

    searchForm.initAutocomplete(
        '<?php echo $this->helper('factfinder_suggest')->getSuggestUrl() ?>',
        'search_autocomplete'
    );

    //]]>
</script>
