<?php if(Mage::helper('factfinder/search')->getIsEnabled()):?>
<div class="ffcampaigntext"><?php echo $this->getText(); ?></div>

<?php
	// this is an example, how to use the pushed products
	$pushedProducts = $this->getPushedProductsCollection()->load()->toArray();
	if (!empty($pushedProducts)) {
		//customize here the pushed products output
		echo ' <!-- ';
		var_dump($pushedProducts);
		echo ' --> ';
	}
?>
<?php endif;?>