<?php
/**
 * FACTFinder_Tracking
 *
 * @category Mage
 * @package FACTFinder_Tracking
 * @author Flagbit Magento Team <magento@flagbit.de>
 * @copyright Copyright (c) 2015 Flagbit GmbH & Co. KG
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link http://www.flagbit.de
 *
 */
?>
<script type="text/javascript">
var factfinderRecommendationTracking = new FactfinderTracking(
    '.col-main',
    $H(<?php echo $this->getJsonDataObject();?>),
    $H(<?php echo $this->getJsonUrlToIdMappingObject();?>),
    '<?php echo $this->getUrl(Mage::helper('factfinder_tracking')->getTrackingUrlPath()) ?>',
    false
);

Event.observe(document, 'dom:loaded', function(event) {
    factfinderRecommendationTracking.init();
});

</script>