<?php
/**
 * Flagbit_FactFinder
 *
 * @category  Mage
 * @package   Flagbit_FactFinder
 * @copyright Copyright (c) 2010 Flagbit GmbH & Co. KG (http://www.flagbit.de/)
 */

/**
 * Template to replace Javascript Suguest
 * 
 * @category  Mage
 * @package   Flagbit_FactFinder
 * @copyright Copyright (c) 2010 Flagbit GmbH & Co. KG (http://www.flagbit.de/)
 * @author    Joerg Weller <weller@flagbit.de>
 * @version   $Id$
 */
 
// array_filter() is used to turn a one-element array into an empty array in the case of an empty config-string
$channels = array_filter(explode(';', Mage::getStoreConfig('factfinder/search/secondary_channels')));
?>
<form id="search_mini_form" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" method="get">
    <div class="form-search">
        <label for="search"><?php echo $this->__('Search:') ?></label>
        <input id="search" type="text" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>" value="<?php echo $this->helper('catalogsearch')->getEscapedQueryText() ?>" class="input-text" />
        <button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><span><span><?php echo $this->__('Search') ?></span></span></button>
        <div id="search_autocomplete" class="search-autocomplete"></div>
		<?php foreach($channels as $channel):?>
			<div id="search_autocomplete_<?php echo $channel; ?>" class="search-autocomplete"></div>
		<?php endforeach; ?>
        <script type="text/javascript">
        //<![CDATA[
            <?php if (Mage::helper('factfinder/search')->getIsEnabled(false, 'suggest')):?>
				var searchForm = new FactFinderSuggest('search_mini_form', 'search', '<?php echo $this->__('Search entire store here...') ?>');
				searchForm.initAutocomplete('<?php echo $this->helper('factfinder/search')->getSuggestUrl() ?>', 'search_autocomplete');
				
				var secondarySearchForms = new Array(<?php echo count($channels); ?>);
				<?php foreach($channels as $id => $channel): ?>
					secondarySearchForms[<?php echo $id; ?>] = new FactFinderSuggest('search_mini_form', 'search', '<?php echo $this->__('Search entire store here...') ?>');
					secondarySearchForms[<?php echo $id; ?>].initAutocomplete('<?php echo $this->helper('factfinder/search')->getSecondarySuggestUrl($channel) ?>', 'search_autocomplete_<?php echo $channel; ?>');
				<?php endforeach; ?>
            <?php else:?>
				var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search entire store here...') ?>');
				searchForm.initAutocomplete('<?php echo $this->helper('catalogsearch')->getSuggestUrl() ?>', 'search_autocomplete');
            <?php endif;?>
        //]]>
        </script>
    </div>
</form>
