<?php
/**
 * Flagbit_FactFinder
 *
 * @category  Mage
 * @package   Flagbit_FactFinder
 * @copyright Copyright (c) 2010 Flagbit GmbH & Co. KG (http://www.flagbit.de/)
 */

/**
 * Add FACT-Finder Logo to Search Result
 * 
 * @category  Mage
 * @package   Flagbit_FactFinder
 * @copyright Copyright (c) 2010 Flagbit GmbH & Co. KG (http://www.flagbit.de/)
 * @author    Joerg Weller <weller@flagbit.de>
 * @version   $Id$
 */
?>
 <?php if(Mage::helper('factfinder/search')->getIsEnabled()):?>
 	<div style="text-align:center;margin: 10px auto;"><a href="http://www.fact-finder.de"><img src="http://www.fact-finder.de/files/fact_finder_conversion.jpg" border="0" alt="on-site search & navigation – conversion engine FACT-Finder" target="_blank" width="116" height="35"></a></div>
<?php endif;?>
