<?php
/**
 * Flagbit_FactFinder
 *
 * @category  Mage
 * @package   Flagbit_FactFinder
 * @copyright Copyright (c) 2010 Flagbit GmbH & Co. KG (http://www.flagbit.de/)
 */

/**
 * Add FACT-Finder SCIC
 *
 * @category  Mage
 * @package   Flagbit_FactFinder
 * @copyright Copyright (c) 2010 Flagbit GmbH & Co. KG (http://www.flagbit.de/)
 * @author    Joerg Weller <weller@flagbit.de>
 * @version   $Id$
 */
?>
<script type="text/javascript">
var factfinderSCIC = new FactfinderSCIC(
    '.col-main',
    $H(<?php echo $this->getJsonDataObject();?>),
    $H(<?php echo $this->getJsonUrlToIdMappingObject();?>),
    '<?php echo $this->getUrl('factfinder/proxy/scic'); ?>'
);

Event.observe(document, 'dom:loaded', function(event) {
	factfinderSCIC.init();
});
</script>