<?php
/**
 * Flagbit_FactFinder
 *
 * @category  Mage
 * @package   Flagbit_FactFinder
 * @copyright Copyright (c) 2010 Flagbit GmbH & Co. KG (http://www.flagbit.de/)
 */

/**
 * Add a list of secondary results to Search Result
 * 
 * @category  Mage
 * @package   Flagbit_FactFinder
 * @copyright Copyright (c) 2010 Flagbit GmbH & Co. KG (http://www.flagbit.de/)
 * @author    Joerg Weller <weller@flagbit.de>
 * @version   $Id$
 */
?>
<?php

// array_filter() is used to turn a one-element array into an empty array in the case of an empty config-string
$channels = array_filter(explode(';', Mage::getStoreConfig('factfinder/search/secondary_channels')));

if(Mage::helper('factfinder/search')->getIsEnabled() && !empty($channels)):

?>

<div>
<?php echo $this->__('Secondary Result'); ?>:
<br><br>
<?php
$result = $this->getSecondaryResult($channels[0]);
foreach($result AS $record)
{
	echo $record->getValue("Title")."<br/>";
}
?>
</div>
 	
<?php endif;?>
