<?php
/**
 * Flagbit_FactFinder
 *
 * @category  Mage
 * @package   Flagbit_FactFinder
 * @copyright Copyright (c) 2010 Flagbit GmbH & Co. KG (http://www.flagbit.de/)
 */

/**
 * Add a list of secondary results to Search Result
 * 
 * @category  Mage
 * @package   Flagbit_FactFinder
 * @copyright Copyright (c) 2010 Flagbit GmbH & Co. KG (http://www.flagbit.de/)
 * @author    Joerg Weller <weller@flagbit.de>
 * @version   $Id$
 */
?>
<?php if(Mage::helper('factfinder/search')->getIsEnabled()):?>

<div>
<?php echo $this->__('Secondary Result'); ?>:
<br><br>
<?php
$result = $this->getSecondaryResult("dev-content");
foreach($result AS $record)
{
	echo $record->getValue("Title")."<br/>";
}
?>
</div>
 	
<?php endif;?>
