<?php
/**
* FACTFinder_Campaigns
*
* @category Mage
* @package FACTFinder_Campaigns
* @author Flagbit Magento Team <magento@flagbit.de>
* @copyright Copyright (c) 2015, Flagbit GmbH & Co. KG
* @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
* @link http://www.flagbit.de
*/
?>
<?php $questions = $this->getActiveQuestions() ?>
<?php if (!empty($questions)): ?>
    <?php foreach ($questions as $question): ?>
        <div class="factfinder-advisorCampaign">
            <p class="factfinder-advisorCampaign-question"><?php echo $question->getText() ?></p>
            <ul>
                <?php foreach ($question->getAnswers() as $answer): ?>
                    <?php //foreach ($answer->getFollowUpQuestions() as $question): ?>
                        <?php //$question->getAnswers(); ?>
                    <?php //endforeach; ?>
                    <li>
                        <a class="factfinder-advisorCampaign-answer" href="<?php echo $answer->getUrl() ?>">
                            <?php echo $answer->getText() ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endforeach; ?>
<?php endif; ?>