<?php
/**
 * FACTFinder_Core
 *
 * @category Mage
 * @package FACTFinder_Core
 * @author Flagbit Magento Team <magento@flagbit.de>
 * @copyright Copyright (c) 2015 Flagbit GmbH & Co. KG
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link http://www.flagbit.de
 *
 */
 ?>
<?php
echo $this->__('Another export is already running. Please wait for it to finish before you start a new export.');
?>
<br />
<?php
echo $this->__('If you receive this message after another export has failed, please delete the file "ffexport.lock" within your Magento directory.');
