<?php
/**
 * FACTFinder_Asn
 *
 * @category Mage
 * @package FACTFinder_Asn
 * @author Flagbit Magento Team <magento@flagbit.de>
 * @copyright Copyright (c) 2015, Flagbit GmbH & Co. KG
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link http://www.flagbit.de
 */
/**
 * Slider HTML Template
 */
?>
<ol>
    <?php foreach ($this->getItems() as $_item): ?>
        <li>
            <div id="<?php echo base64_encode($this->getValue());?>" style="width: 170px;padding:10px 0px;"></div>
            <script type="text/javascript" language="javascript">
                //<![CDATA[

                Event.observe(document, 'ffslider:init', function(event){
                        oneTouchSlider.addSlider({
                            hostElementId:'<?php echo base64_encode($this->getValue());?>',
                            leftBorder: <?php echo $this->getAbsoluteMin();?>,
                            rightBorder: <?php echo $this->getAbsoluteMax();?>,
                            currentLeft: <?php echo $this->getSelectedMin();?>,
                            currentRight: <?php echo $this->getSelectedMax();?>,
                            unit:"<?php echo $this->getUnit();?>",
                            callback:function(left, right){
                                var url = decodeURI('<?php echo $_item->getUrl() ?>');
                                window.location.href= url.replace('[VALUE]',left + ' - ' + right);
                            }
                        });
                    }
                );
                //]]>
            </script>
        </li>
    <?php endforeach ?>
</ol>
